#! /bin/bash

__init__() {
    export __OMNI_MODS="$__OMNI/mods"
    export __OMNI_CONF="$__OMNI/conf"
    export __OMNI_TOOLS="$__OMNI/tools"
    export __OMNI_CONTEXTS="$__OMNI/contexts"

    [[ -d "$__OMNI_TOOLS" ]] || mkdir -p "$__OMNI_TOOLS" 2>/dev/null || true
    export OMNI="${OMNI:-$HOME/.omni}"
    export OMNIRC="${OMNIRC:-$OMNI/omnirc}"

    mkdir -p $OMNI && touch $OMNIRC && source "$OMNIRC"

    source "$__OMNI_MODS/helper" && __helper__

    __declare --dict ENVS ENV_VARS ENV_LAZY ENV_OPEN ENV_COMMA PROVIDERS ENV_PROVIDERS TOOLS ENV_TOOLS IMPORTS CONTEXTS

    __load omni --from "$__OMNI_MODS/omni" --lazy && unset -f omni.__compl__

    local files
    shopt -s nullglob
    files=("$__OMNI_TOOLS"/*)
    shopt -u nullglob
    files=("${files[@]##*/}")
    local OIFS="$IFS"
    IFS=,
    export TOOLS_LIST="${files[*]}"
    IFS="$OIFS"

    export ENV="${__ENV}"
    if [[ -n "$ENV" ]]; then
        omni envs use "$ENV" --global
    fi
}

__init__
unset -f __init__
