#! /bin/bash

__omni() {
    __compl_omni() {
        local cur prev
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"

        if [[ "${COMP_CWORD}" == 1 ]]; then
            COMPREPLY=( $(compgen -W "envs scripts conf init --help" -- "$cur") )
            return 0
        fi

        local cmd="${COMP_WORDS[1]}"
        case "$cmd" in
            envs)
                __compl_envs ;;
            scripts)
                __compl_scripts ;;
            init)
                if [[ "${COMP_CWORD}" == 2 ]]; then
                    COMPREPLY=( $(compgen -W "-c --conf" -- "$cur") )
                fi
                ;;
        esac
    }
    complete -F __compl_omni omni

    omni() {
        local cmd="$1"
        case "$cmd" in
            envs)
                shift
                eval "envs \"\$@\""
                ;;
            scripts)
                shift
                eval "scripts \"\$@\""
                ;;
            conf)
                echo "TO BE IMPLEMENTED"
                ;;
            init)
                shift
                local conf_file=""
                
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        -c=*|--conf=*) conf_file="${1#*=}" ;;
                        -c|--conf)     conf_file="$2"; shift ;;
                    esac
                    shift
                done
                
                export __OMNIRC="${conf_file:-${__OMNIRC:-$HOME/.omnirc}}"
                
                if [[ -n "$__OMNI" && -f "$__OMNI/init" ]]; then
                    source "$__OMNI/init"
                    echo "Initialized omni using config: $__OMNIRC"
                else
                    echo "Error: \$__OMNI is not set or omni/init not found." >&2
                    return 1
                fi
                ;;
            --help|-h)
                echo "omni envs ..."
                echo "omni scripts ..."
                echo "omni conf"
                echo "omni init [-c/--conf <some_omnirc>]"
                ;;
            *)
                echo "Unknown omni command: $cmd" >&2
                return 1
                ;;
        esac
    } 
}
