#! /bin/bash

__omni.envs__() {
    __omni__.envs.__help__() {
        echo """ABOUT:
    omni environments manager

USAGE:
    omni envs <command> [args]

COMMANDS:
    ls
    set     <env> -p/--path=<path> [-b/--bin=<bin>] [-t/--tmp=<tmp>] [-s/--sec=<sec>] [-m/--mnt=<mnt>]
    get     [<env>]
    rm      <env>
    use     <env> [-g/--global] [-b/--builtins=ls,cd...]""" >&2
    }

    __global() {
        local val="$1" rcfile="${__OMNIRC:-$HOME/.omnirc}"
        local content="" found=0

        if [[ -f "$rcfile" ]]; then
            while IFS= read -r line || [[ -n "$line" ]]; do
                if [[ "$line" == __ENV=* ]]; then
                    [[ -n "$val" ]] && content+="__ENV=\"$val\""$'\n'
                    found=1
                else
                    content+="$line"$'\n'
                fi
            done < "$rcfile"
        fi

        if [[ $found -eq 0 && -n "$val" ]]; then
            content+="__ENV=\"$val\""$'\n'
        fi

        if [[ -n "$content" || -f "$rcfile" ]]; then
            printf "%s" "$content" > "$rcfile"
        fi
    }

    __omni__.envs.init() {
        local t_env="${1:-$ENV}"
        local env_path=""
        
        if [[ -n "$t_env" && -n "${ENVS[$t_env]}" ]]; then
            env_path="${ENVS[$t_env]}"
        elif [[ -n "$ENV_PATH" ]]; then
            env_path="$ENV_PATH"
        fi
        
        [[ -z "$env_path" ]] && __log "<env> is mandatory or no active environment" -t error -l envs && return 1
        
        if [[ -f "$env_path/init" ]]; then
            source "$env_path/init"
            __log "Sourced $env_path/init" -t success -l envs
        else
            __log "$env_path/init not found" -t error -l envs
            return 1
        fi
    }

    __omni__.envs.ls() { 
        for env in ${ENVS[@]}; do echo $env; done
    }

    __omni__.envs.set() {
        _target_name="$1"; shift
        env_path="" bin="" tmp="" sec="" mnt=""
        while [[ $# -gt 0 ]]; do
            case "$1" in
                -p=*|--path=*) env_path="${1#*=}" ;;
                -p|--path)     env_path="$2"; shift ;;
                -b=*|--bin=*)  bin="${1#*=}" ;;
                -b|--bin)      bin="$2"; shift ;;
                -t=*|--tmp=*)  tmp="${1#*=}" ;;
                -t|--tmp)      tmp="$2"; shift ;;
                -s=*|--sec=*)  sec="${1#*=}" ;;
                -s|--sec)      sec="$2"; shift ;;
                -m=*|--mnt=*)  mnt="${1#*=}" ;;
                -m|--mnt)      mnt="$2"; shift ;;
            esac
            shift
        done
        [[ -z "$_target_name" ]] && __log "<env> mandatory" -t error -l envs && return 1
        [[ -z "$env_path" ]] && __log "--path mandatory" -t error -l envs && return 1
        echo "ENVS+=($_target_name)" > $__OMNIRC

        __update "ENV_VARS" "$_target_name" "path:$env_path,bin:$bin,tmp:$tmp,sec:$sec,mnt:$mnt" "set"
        __log "Environment '$_target_name' registered." -t success -l envs
    }

    __omni__.envs.get() {
        _target_name="${1:-$ENV}"
        [[ -z "$_target_name" ]] && __log "<env> mandatory" -t error -l envs && return 1
        [[ -z "${ENVS[$_target_name]}" ]] && __log "env '$_target_name' not registered" -t error -l envs && return 1
        str=",${ENV_VARS[$_target_name]},"
        
        local e_path="${str#*,path:}"
        echo "ENV_PATH=${e_path%%,*}"
        local e_bin="${str#*,bin:}"
        echo "BIN=${e_bin%%,*}"
        local e_tmp="${str#*,tmp:}"
        echo "TMP=${e_tmp%%,*}"
        local e_sec="${str#*,sec:}"
        echo "SEC=${e_sec%%,*}"
        local e_mnt="${str#*,mnt:}"
        echo "MNT=${e_mnt%%,*}"
    }

    __omni__.envs.rm() {
        _target_name="$1"
        [[ -z "$_target_name" ]] && __log "<env> mandatory" -t error -l envs && return 1
        if ! __is env "$_target_name"; then __log "'$_target_name' invalid" -t error -l envs; return 1; fi
        [[ "$__ENV" == "$_target_name" ]] && __global ""
        __update "ENVS" "$_target_name" "" "rm"
        __update "ENV_VARS" "$_target_name" "" "rm"
        __update "ENV_LAZY" "$_target_name" "" "rm"
        __update "ENV_COMMA" "$_target_name" "" "rm"
        __update "ENV_OPEN" "$_target_name" "" "rm"
        __update "ENV_PROVIDERS" "$_target_name" "" "rm"
        __update "ENV_TOOLS" "$_target_name" "" "rm"
        __log "Environment '$_target_name' removed." -t success -l envs
    }

    __omni__.envs.use() {
        _target_name="$1"
        if [[ -z "$_target_name" ]]; then _target_name="$ENV"; fi
        if [[ -z "$_target_name" ]]; then __log "<env> mandatory" -t error -l envs; return 1; fi
        shift
        set_global=false b_list=""
        while [[ $# -gt 0 ]]; do
            case "$1" in
                -g|--global) set_global=true ;;
                -b=*|--builtins=*) b_list="${1#*=}" ;;
                -b|--builtins) b_list="$2"; shift ;;
            esac
            shift
        done
        if ! __is env "$_target_name"; then __log "could not load env '$_target_name': not registered." -t error -l envs; return 1; fi
        export ENV="$_target_name"
        str=",${ENV_VARS[$_target_name]},"

        export ENV_PATH="${str#*,path:}" && export ENV_PATH="${ENV_PATH%%,*}"
        export BIN="${str#*,bin:}" && export BIN="${BIN%%,*}"
        export TMP="${str#*,tmp:}" && export TMP="${TMP%%,*}"
        export SEC="${str#*,sec:}" && export SEC="${SEC%%,*}"
        export MNT="${str#*,mnt:}" && export MNT="${MNT%%,*}"
        [[ -n "$BIN" ]] && export PATH="$PATH:$BIN"
        if $set_global; then __global "$_target_name"; export __ENV="$_target_name" __ENV_PATH="$ENV_PATH"; fi
        
        source "$__OMNI_MODS/omni.d/builtins"
        if declare -f __omni.builtins__ >/dev/null 2>&1; then __omni.builtins__; fi
        
        if [[ -z "$b_list" ]]; then 
            if declare -f __omni__.builtins.__init__ >/dev/null 2>&1; then __omni__.builtins.__init__; fi
        else 
            for b in ${b_list//,/ }; do 
                if declare -f __omni__.builtins.use >/dev/null 2>&1; then __omni__.builtins.use "$b" -e "$_target_name"; fi
            done
        fi
        
        active_tools=$(__list tools --env "$_target_name" 2>/dev/null)
        if [[ -n "$active_tools" ]]; then 
            for t_name in ${active_tools//,/ }; do 
                __load tool "$t_name" --from "$__OMNI_TOOLS/$t_name" --lazy
            done
        fi
        
        if declare -f __init >/dev/null 2>&1; then
            if declare -f __omni__.builtins >/dev/null 2>&1; then __init __omni__.builtins; fi
        fi

        [[ -f $ENV_PATH/init ]] && source $ENV_PATH/init
    }

    __omni__.envs() {
        local cmd="$1"
        [[ -z "$cmd" || "$cmd" == "--help" || "$cmd" == "-h" ]] && { __omni__.envs.__help__; return 0; }
        shift

        case "$cmd" in
            init) __omni__.envs.init "$@" ;;
            ls)   __omni__.envs.ls   "$@" ;;
            set)  __omni__.envs.set  "$@" ;;
            rm)   __omni__.envs.rm   "$@" ;;
            get)  __omni__.envs.get  "$@" ;;
            use)  __omni__.envs.use  "$@" ;;
            *) declare -f __log >/dev/null && __log "Unknown command '$cmd' for __omni__.envs" -t error -l "__omni__.envs" || echo "__omni__.envs: Unknown command '$cmd'" >&2; return 1 ;;
        esac
    }

    __omni__.envs.__compl__() {
        local cur="${COMP_WORDS[COMP_CWORD]}" prev="${COMP_WORDS[COMP_CWORD-1]}" base_cmd="${COMP_WORDS[1]:-}"
        if [[ "${COMP_CWORD}" == 1 ]]; then
            COMPREPLY=( $(compgen -W "ls get set rm use init --help -h" -- "$cur") )
            return 0
        fi
        local flags=""
        case "$base_cmd" in
            set) flags="--path --bin --tmp --sec --mnt" ;;
            use) flags="--global --builtins" ;;
        esac
        if [[ "$base_cmd" == "set" ]]; then
            COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
            return 0
        fi
        if [[ "$base_cmd" == "use" || "$base_cmd" == "rm" || "$base_cmd" == "get" || "$base_cmd" == "init" ]]; then
            COMPREPLY=( $(compgen -W "${ENVS[*]} $flags" -- "$cur") )
            return 0
        fi
    }

    __omni__.envs.__init__() {
        __compl __omni__.envs
    }

}
