#! /bin/bash

__exports(){
    BIN=$1
    TMP=$2
    SEC=$3

    local __CWD="\[\033[37m\]\w\[\033[00m\]"
    export PS1="${__CWD}\$ "
    export LS_COLORS=$LS_COLORS:'di=0;94:'

    export EDITOR=vim
    export BROWSER=firefox

    [ -n $BIN ] && export BIN=$BIN && export PATH=$PATH:$BIN
    [ -n $TMP ] && export TMP=$TMP
    [ -n $SEC ] && export SEC=$SEC
}
