#! /bin/bash

function __load(){
    declare -Ag LOAD
    declare -Ag GLOBAL
    function load() {
        function __load__() {
            local name="$1"
            local entry="${USE['$name']}"
            local data=($(echo $entry | tr ':' ' '))
            local path=${__data[0]}
            local func=${__data[1]}
            [ -z $func ] && func=$name

            if [[ ! -f "$path" ]]; then
                echo "error: file not found '$path'."
                return 1
            fi
            eval "function $name() { source \"$path\" && $name \"\$@\"; }"
        }
        if [[ " $@ " =~ " * " ]]; then
            for name in "${!LOAD[@]}"; do
                __load__ "$name"
            done
        fi
        for name in "${!LOAD[@]}"; do
            if [[ " $@ " =~ " $name " ]]; then
                __load__ "$name"
                return 0
            fi
        done
    }

    function global(){
        if [[ " $@ " =~ " * " ]]; then
            for name in "${!GLOBAL[@]}"; do
                source "$name"
            done
            return 0
        fi
        for name in "${!GLOBAL[@]}"; do
            if [[ " $@ " =~ " $name " ]]; then
                source "$name"
                return 0
            fi
        done 
    }
}
