#! /bin/bash

__dot() {
    dot() {
        case "$1" in
            "")
                ls ;;
            "-"|"...")
                shift && back && ls ;;
            "..")
                shift && cd .. && ls ;;
            ".")
                shift && home ;;
            ",")
                shift && la "$@" ;;
            *)
                if [[ -d "$1" ]]; then
                    cd "$1"
                    shift
                    ls "$@"
                elif [[ -f "$1" ]]; then
                    open "$1"
                else
                    ls "$@"
                fi
                ;;
        esac
    }

    __dot_aliases() {
        alias .='dot'
        alias ..="dot .."
        alias .,='dot ,'
        alias .f='lf'
        alias .d='ld'

    }

    __dot_compl() {
        local cur
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"

        if [[ "${COMP_CWORD}" == 1 && "$cur" == .* || "$cur" == , || "$cur" == - ]]; then
            COMPREPLY=( $(compgen -W "- ... .. . ," -- "$cur") )
            return 0
        fi
        
    }

    __dot_init() {
        __aliases  dot
        __complete dot
        __clean    dot
    }
}
