#! /bin/bash

__global() {
    global() {
        local name="$1" path="" t_env="$ENV"
        shift
        
        while [[ $# -gt 0 ]]; do
            case "$1" in 
                --path=*) path="${1#*=}" ;;
                --path) path="$2"; shift ;; 
                --env=*)  t_env="${1#*=}" ;; 
                --env) t_env="$2"; shift ;;
            esac
            shift
        done
        
        [[ -z "$t_env" ]] && echo "Error: no env was set (use --env or export ENV)" >&2 && return 1
        
        if [[ -z "$path" && -n "$name" ]]; then
            path="$(__get global "$name" --env "$t_env")"
            [[ $? -ne 0 ]] && return 1
        fi

        if [[ -f "$path" ]]; then
            source "$path"
            type "__${name}" &>/dev/null && eval "__${name}"
        else
            echo "Error: global file '$path' not found for '$name'." >&2
            return 1
        fi
    }

    __global_compl() {
        local cur prev
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"

        if [[ "$prev" == "--env" ]]; then
            COMPREPLY=( $(compgen -W "${!ENVS[*]}" -- "$cur") )
            return 0
        fi

        if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "--path --env" -- "$cur") )
            return 0
        fi
    }

    __global_init() {
        __complete global
        __clean    global
    }
}
